// Package account provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package account

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Field string `json:"field"`
	Issue string `json:"issue"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code          string         `json:"code"`
	CorrelationId string         `json:"correlationId"`
	Details       *[]ErrorDetail `json:"details,omitempty"`
	Message       string         `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// InterestDetailsResponse defines model for InterestDetailsResponse.
type InterestDetailsResponse struct {
	Currency     string  `json:"currency"`
	CustomerId   string  `json:"customerId"`
	InterestRate float64 `json:"interestRate"`
	InterestType string  `json:"interestType"`
	ProductCode  string  `json:"productCode"`
}

// CorrelationIdHeader defines model for CorrelationIdHeader.
type CorrelationIdHeader = string

// GetInterestDetailsParams defines parameters for GetInterestDetails.
type GetInterestDetailsParams struct {
	XCorrelationId *CorrelationIdHeader `json:"X-Correlation-Id,omitempty"`
}
